"""NFO file parsers for music video metadata."""

from .artist_parser import ArtistNFOParser
from .models import ArtistNFO, MusicVideoNFO
from .musicvideo_parser import MusicVideoNFOParser
from .imvdb_models import (
    IMVDbArtist,
    IMVDbSource,
    IMVDbDirector,
    IMVDbCredit,
    IMVDbCast,
    IMVDbVideo,
    IMVDbEntityVideo,
    IMVDbEntity,
    IMVDbEntitySearchResult,
    IMVDbEntitySearchResponse,
    IMVDbVideoSearchResult,
    IMVDbPagination,
    VideoNotFoundError,
    EmptySearchResultsError,
)
from .imvdb_parser import IMVDbParser
from .discogs_models import (
    DiscogsArtist,
    DiscogsTrack,
    DiscogsImage,
    DiscogsVideo,
    DiscogsLabel,
    DiscogsMaster,
    DiscogsRelease,
    DiscogsSearchResultItem,
    DiscogsSearchResult,
    DiscogsArtistRelease,
    DiscogsArtistReleasesResult,
    DiscogsPagination,
    MasterNotFoundError,
    ReleaseNotFoundError,
)
from .discogs_parser import DiscogsParser

__all__ = [
    "ArtistNFO",
    "MusicVideoNFO",
    "ArtistNFOParser",
    "MusicVideoNFOParser",
    "IMVDbArtist",
    "IMVDbSource",
    "IMVDbDirector",
    "IMVDbCredit",
    "IMVDbCast",
    "IMVDbVideo",
    "IMVDbEntityVideo",
    "IMVDbEntity",
    "IMVDbEntitySearchResult",
    "IMVDbEntitySearchResponse",
    "IMVDbVideoSearchResult",
    "IMVDbPagination",
    "IMVDbParser",
    "VideoNotFoundError",
    "EmptySearchResultsError",
    "DiscogsArtist",
    "DiscogsTrack",
    "DiscogsImage",
    "DiscogsVideo",
    "DiscogsLabel",
    "DiscogsMaster",
    "DiscogsRelease",
    "DiscogsSearchResultItem",
    "DiscogsSearchResult",
    "DiscogsArtistRelease",
    "DiscogsArtistReleasesResult",
    "DiscogsPagination",
    "DiscogsParser",
    "MasterNotFoundError",
    "ReleaseNotFoundError",
]
