"""NFO file parsers for music video metadata."""

from .artist_parser import ArtistNFOParser
from .models import ArtistNFO, MusicVideoNFO, FeaturedArtistConfig
from .musicvideo_parser import MusicVideoNFOParser
from .imvdb_models import (
    IMVDbArtist,
    IMVDbSource,
    IMVDbDirector,
    IMVDbCredit,
    IMVDbCast,
    IMVDbVideo,
    IMVDbEntityVideo,
    IMVDbEntity,
    IMVDbEntitySearchResult,
    IMVDbEntitySearchResponse,
    IMVDbVideoSearchResult,
    IMVDbPagination,
    VideoNotFoundError,
    EmptySearchResultsError,
)
from .imvdb_parser import IMVDbParser
from .discogs_models import (
    DiscogsArtist,
    DiscogsTrack,
    DiscogsImage,
    DiscogsVideo,
    DiscogsLabel,
    DiscogsMaster,
    DiscogsRelease,
    DiscogsSearchResultItem,
    DiscogsSearchResult,
    DiscogsArtistRelease,
    DiscogsArtistReleasesResult,
    DiscogsPagination,
    MasterNotFoundError,
    ReleaseNotFoundError,
)
from .discogs_parser import DiscogsParser
from .ffprobe_models import (
    FFProbeFormat,
    FFProbeVideoStream,
    FFProbeAudioStream,
    FFProbeMediaInfo,
)
from .ffprobe_parser import FFProbeParser
from .musicbrainz_models import (
    MusicBrainzTag,
    MusicBrainzAlias,
    MusicBrainzArea,
    MusicBrainzLifeSpan,
    MusicBrainzArtist,
    MusicBrainzArtistCredit,
    MusicBrainzReleaseGroup,
    MusicBrainzReleaseEvent,
    MusicBrainzTrack,
    MusicBrainzMedia,
    MusicBrainzRelease,
    MusicBrainzRecording,
    MusicBrainzRecordingSearchResponse,
    MusicBrainzArtistSearchResponse,
    MusicBrainzISRCResponse,
    RecordingNotFoundError,
)
from .musicbrainz_parser import MusicBrainzParser

__all__ = [
    "ArtistNFO",
    "MusicVideoNFO",
    "FeaturedArtistConfig",
    "ArtistNFOParser",
    "MusicVideoNFOParser",
    "IMVDbArtist",
    "IMVDbSource",
    "IMVDbDirector",
    "IMVDbCredit",
    "IMVDbCast",
    "IMVDbVideo",
    "IMVDbEntityVideo",
    "IMVDbEntity",
    "IMVDbEntitySearchResult",
    "IMVDbEntitySearchResponse",
    "IMVDbVideoSearchResult",
    "IMVDbPagination",
    "IMVDbParser",
    "VideoNotFoundError",
    "EmptySearchResultsError",
    "DiscogsArtist",
    "DiscogsTrack",
    "DiscogsImage",
    "DiscogsVideo",
    "DiscogsLabel",
    "DiscogsMaster",
    "DiscogsRelease",
    "DiscogsSearchResultItem",
    "DiscogsSearchResult",
    "DiscogsArtistRelease",
    "DiscogsArtistReleasesResult",
    "DiscogsPagination",
    "DiscogsParser",
    "MasterNotFoundError",
    "ReleaseNotFoundError",
    "FFProbeFormat",
    "FFProbeVideoStream",
    "FFProbeAudioStream",
    "FFProbeMediaInfo",
    "FFProbeParser",
    "MusicBrainzTag",
    "MusicBrainzAlias",
    "MusicBrainzArea",
    "MusicBrainzLifeSpan",
    "MusicBrainzArtist",
    "MusicBrainzArtistCredit",
    "MusicBrainzReleaseGroup",
    "MusicBrainzReleaseEvent",
    "MusicBrainzTrack",
    "MusicBrainzMedia",
    "MusicBrainzRelease",
    "MusicBrainzRecording",
    "MusicBrainzRecordingSearchResponse",
    "MusicBrainzArtistSearchResponse",
    "MusicBrainzISRCResponse",
    "MusicBrainzParser",
    "RecordingNotFoundError",
]
